from kiteconnect import KiteConnect, KiteTicker
import pandas as pd
import datetime
from itertools import cycle, islice
import re

# Exhaustive list of all the stocks for which data is needed
STOCK_LIST = \
["NIFTY", "BANKNIFTY", "FINNIFTY","AARTIIND","ACC","ADANIENT"
,"ADANIPORTS","ALKEM","AMARAJABAT","AMBUJACEM","APLLTD","APOLLOHOSP"
,"APOLLOTYRE","ASHOKLEY","ASIANPAINT","AUBANK","AUROPHARMA"
,"AXISBANK","BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BALKRISIND","BANDHANBNK"
,"BANKBARODA","BATAINDIA","BEL","BERGEPAINT","BHARATFORG","BHARTIARTL"
,"BHEL","BIOCON","BOSCHLTD","BPCL","BRITANNIA","CADILAHC","CANBK","CHOLAFIN"
,"CIPLA","COALINDIA","COFORGE","COLPAL","CONCOR","CUB","CUMMINSIND","DABUR"
,"DEEPAKNTR","DIVISLAB","DLF","DRREDDY","EICHERMOT","ESCORTS","EXIDEIND"
,"FEDERALBNK","FINNIFTY","GAIL","GLENMARK","GMRINFRA","GODREJCP","GODREJPROP"
,"GRANULES","GRASIM","GUJGASLTD","HAVELLS","HCLTECH","HDFC","HDFCAMC"
,"HDFCBANK", "HDFCLIFE","HEROMOTOCO","HINDALCO","HINDPETRO","HINDUNILVR"
,"IBULHSGFIN","ICICIBANK","ICICIGI","ICICIPRULI","IDEA","IDFCFIRSTB","IGL"
,"INDIGO","INDUSINDBK","INDUSTOWER","INFY","IOC","IRCTC","ITC","JINDALSTEL"
,"JSWSTEEL","JUBLFOOD","KOTAKBANK","L&TFH","LALPATHLAB","LICHSGFIN","LT"
,"LTI","LTTS","LUPIN","M&M","M&MFIN","MANAPPURAM","MARICO","MARUTI"
,"MCDOWELL-N","MFSL","MGL","MINDTREE","MOTHERSUMI","MPHASIS","MRF","MUTHOOTFIN"
,"NAM-INDIA","NATIONALUM","NAUKRI","NAVINFLUOR","NESTLEIND","NMDC","NTPC"
,"ONGC","PAGEIND","PEL","PETRONET","PFC","PFIZER","PIDILITIND","PIIND","PNB"
,"POWERGRID","PVR","RAMCOCEM","RBLBANK","RECLTD","RELIANCE","SAIL","SBILIFE"
,"SBIN","SHREECEM","SIEMENS","SRF","SRTRANSFIN","SUNPHARMA","SUNTV","TATACHEM"
,"TATACONSUM","TATAMOTORS","TATAPOWER","TATASTEEL","TCS","TECHM","TITAN"
,"TORNTPHARM","TORNTPOWER","TRENT","TVSMOTOR","UBL","ULTRACEMCO","UPL","VEDL"
,"VOLTAS","WIPRO","ZEEL"]


access_token = '###############' # changes every day
key_secret = '********************'

